import "UI/MyItem.idl";

namespace MyApp
{
    [default_interface]
    runtimeclass MyViewModel
    {
        static MyViewModel Instance();

        MyViewModel();

        Windows.Foundation.Collections.IObservableVector<MyItem> Items{ get; };
		void UpdateItems(void);
    }
}
