namespace MyApp
{
    //-----------------------------------------------------------------------
    runtimeclass MyItem : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        String Title;
        String Subtitle;
        String Description;

        MyItem();
        MyItem(String title, String subtitle, String description);
    }

    runtimeclass MyItemViewPage : 
        Microsoft.UI.Xaml.Controls.Page
    {
        MyItemViewPage();

        Windows.Foundation.Collections.IObservableVector<MyItem> MyItems{ get; };
    }

    //-----------------------------------------------------------------------
    [default_interface]
    runtimeclass Page1 : Microsoft.UI.Xaml.Controls.Page
    {
        Page1();
    }

    //-----------------------------------------------------------------------
    [default_interface]
    runtimeclass Page2 : Microsoft.UI.Xaml.Controls.Page
    {
        Page2();
    }
      
    //-----------------------------------------------------------------------
    [default_interface]
    runtimeclass SettingsPage : Microsoft.UI.Xaml.Controls.Page
    {
        SettingsPage();
    }

    //-----------------------------------------------------------------------
    struct Scenario
    {
        String Title;
        String ClassName;
    };

    runtimeclass MainPage : Microsoft.UI.Xaml.Controls.Page
    {
        MainPage();

        void NotifyUser(String strMessage, Microsoft.UI.Xaml.Controls.InfoBarSeverity severity);
    }

    //-----------------------------------------------------------------------
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
    }
}
