namespace MyApp
{
    // https://github.com/ComCatalin/BookstoreWinRT/blob/master/BookstoreUWP/BookstoreViewModel.cpp
    // https://github.com/OpenKneeboard/OpenKneeboard/tree/master/src/app/app-winui3
    
    //-----------------------------------------------------------------------
    [default_interface]
    runtimeclass MyItem : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        String Title;
        String Subtitle;
        String Description;

        MyItem();
        MyItem(String title, String subtitle, String description);
    }

    //-----------------------------------------------------------------------
    [default_interface]
    runtimeclass MyViewModel
    {
        MyViewModel();

        static MyViewModel Instance();

		Windows.Foundation.Collections.IObservableVector<MyItem> Items{ get; };
    }

    //-----------------------------------------------------------------------
    [default_interface]
    runtimeclass MyItemViewPage : Microsoft.UI.Xaml.Controls.Page
    {
        MyItemViewPage();

        Windows.Foundation.Collections.IObservableVector<MyItem> Items{ get; };
    }

    //-----------------------------------------------------------------------
    [default_interface]
    runtimeclass MyItemEditPage : Microsoft.UI.Xaml.Controls.Page
    {
        MyItemEditPage();
    }

    //-----------------------------------------------------------------------
    [default_interface]
    runtimeclass Page1 : Microsoft.UI.Xaml.Controls.Page
    {
        Page1();
    }

    //-----------------------------------------------------------------------
    [default_interface]
    runtimeclass Page2 : Microsoft.UI.Xaml.Controls.Page
    {
        Page2();
    }
      
    //-----------------------------------------------------------------------
    [default_interface]
    runtimeclass SettingsPage : Microsoft.UI.Xaml.Controls.Page
    {
        SettingsPage();
    }

    //-----------------------------------------------------------------------
    struct Scenario
    {
        String Title;
        String ClassName;
    };

    runtimeclass MainPage : Microsoft.UI.Xaml.Controls.Page
    {
        MainPage();

        void NotifyUser(String strMessage, Microsoft.UI.Xaml.Controls.InfoBarSeverity severity);
    }

    //-----------------------------------------------------------------------
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
    }
}
